blank_issues_enabled: false
contact_links:
  - name: Jellystack Mobile discussions
    url: https://github.com/jellystack/jellystack-mobile/discussions
    about: Ask questions and chat with the community.
